services:
  frontend:
    build:
      context: ./frontend
    image: todoapp-frontend
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
    image: todoapp-backend
    ports:
      - "8080:8080"

networks:
  appnet:
    driver: bridge